source 'https://github.com/CocoaPods/Specs.git'

target 'IBFlurry_Example', :exclusive => true do
  pod 'IBFlurry', :path => '../'
end

target 'IBFlurry_Tests', :exclusive => true do
  pod 'IBFlurry', :path => '../'

  
end
